# logger
log:
  dir: /var/log/pet-paradise
  max-logger-size: 100  # MB
  filename: pet-paradise
  log-level: debug

# databases
mysql:
  host: 7.7.8.8
  port: 3306
  user: root
  password: root
  dbname: pet-paradise
