# logger
log:
  dir: /var/log/pet-paradise
  max-logger-size: 100  # MB
  filename: pet-paradise
  log-level: debug

# databases
mysql:
  host: 172.16.1.1
  port: 3306
  user: root
  password: password
  dbname: pet-paradise

server:
  api: :8080
  agent:
    - 127.0.0.1
