# logger
log:
  dir: /var/log/pet-paradise
  max-logger-size: 100  # MB
  filename: pet-paradise
  log-level: debug

# databases
mysql:
  host: 47.100.114.83
  port: 3306
  user: root
  password: golem
  dbname: pet-paradise

server:
  api: :8080
  agent:
    - 127.0.0.1
